#!/bin/sh

. /etc/homelab-paths.conf

for vers in "8-stream/BaseOS/x86_64/os/" "8-stream/PowerTools/x86_64/os/" "8-stream/extras/x86_64/os/"; do

    mkdir -p ${repobase}/centos${vers}
    #rsync -artP --exclude '*/drpms/*' --delete rsync://${mirror8}/${vers} ${repobase}/centos${vers} 2>&1
    rsync -aqzH --delay-updates --delete-after --exclude '*/drpms/*' rsync://${mirror8}/${vers} ${repobase}/centos${vers} 2>&1
    if [ $? -ne 0 ]; then
        echo "ERROR getting os files from ${mirror8} for ${vers} x64, quitting."
        exit 1
    fi
done
for vers in OL9; do
  #for stream in appstream "baseos/latest" ; do
  # appstream is over 100GB
  for stream in "baseos/latest" ; do
    subpath="${vers}/${stream}/x86_64"
    mkdir -p ${repobase}/${subpath}
    rsync -artP --exclude '*/drpms/*' --exclude '*/debug/*' --exclude '*/getPackageSource/*' --delete rsync://${mirror9}/repo/OracleLinux/${subpath} ${repobase}/${subpath} 2>&1
    if [ $? -ne 0 ]; then
      echo "ERROR getting os files from ${mirror9} for ${subpath}, quitting!"
      exit 4
    fi
  done
done

for vers in "10" ; do
    for stream in "BaseOS" "CRB" "extras"; do
        subpath="${vers}/${stream}/x86_64_v2"
        mkdir -p ${repobase}/${subpath}
        rsync -artP --exclude '*/drpms*' --exclude '*/debug/*' --exclude '*/getPackageSource/*' --delete rsync://${mirror10}/${subpath} ${repobase}/${subpath} 2>&1
        if [ $? -ne 0 ]; then
            echo "ERROR getting os files from ${mirror10} for ${subpath}, quitting!"
            exit 4
        fi
    done
done
chown -R apache:apache ${repobase}
restorecon -r ${repobase}
